// Code generated by goctl. DO NOT EDIT.
package types

type PageReq struct {
	Page int `form:"page"`
	Size int `form:"size"`
}

type DeleteReq struct {
	Id int `json:"id"`
}

type LoginReq struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	CaptchaId string `json:"captcha_id"` // 验证码ID
	Captcha   string `json:"captcha"`    // 用户输入的验证码
}

type LoginRes struct {
	Token      string `json:"token"`
	Username   string `json:"username"`
	Role       string `json:"role"` // 关键字段
	NickName   string `json:"nick_name"`
	DistrictId int    `json:"district_id"` // 方便前端判断归属
}

type CaptchaRes struct {
	CaptchaId string `json:"captcha_id"`
	Base64    string `json:"base64"` // 验证码图片的 Base64 字符串
}

type DistrictInfo struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

type DistrictListRes struct {
	List []DistrictInfo `json:"list"`
}

type PhoneInfo struct {
	Id           int     `json:"id"`
	PhoneNumber  string  `json:"phone_number"`
	Category     string  `json:"category"`
	Grade        int     `json:"grade"`
	Price        float64 `json:"price,optional"` //  看价格
	Status       int     `json:"status"`
	DistrictName string  `json:"district_name"` // <--- 新增：显示区县名
	DistrictId   int     `json:"district_id"`   // <--- 新增：编辑回显用
}

type ImportItem struct {
	PhoneNumber string  `json:"phone_number"`
	Category    string  `json:"category"`
	Grade       int     `json:"grade"`
	Price       float64 `json:"price,optional"` //  新增：允许导入价格
}

type ImportPhonesReq struct {
	List []ImportItem `json:"list"`
}

type ImportPhonesRes struct {
	SuccessCount int `json:"success_count"`
}

type PhoneListReq struct {
	Category    string `form:"category,optional"`
	Grade       int    `form:"grade,optional"`
	Page        int    `form:"page"`
	Size        int    `form:"size"`
	PhoneNumber string `form:"phone_number,optional"` // 查号码
}

type PhoneListRes struct {
	Total int         `json:"total"`
	List  []PhoneInfo `json:"list"`
}

type DeletePhoneReq struct {
	Id int `json:"id"`
}

type UpdatePhoneReq struct {
	Id          int     `json:"id"`
	PhoneNumber string  `json:"phone_number"`
	Category    string  `json:"category"`
	Grade       int     `json:"grade"`
	Price       float64 `json:"price,optional"`       //新增：允许修改价格
	DistrictId  int     `json:"district_id,optional"` // <--- 新增：允许修改关联订单的区县
}

type OrderCreateReq struct {
	CustomerName    string `json:"customer_name"`
	CustomerPhone   string `json:"customer_phone"`
	CustomerAddress string `json:"customer_address"`
	PhoneId         int    `json:"phone_id"`
	DistrictId      int    `json:"district_id"`
}

type OrderItem struct {
	Id              int    `json:"id"`
	CustomerName    string `json:"customer_name"`
	CustomerPhone   string `json:"customer_phone"`
	CustomerAddress string `json:"customer_address"`
	PhoneNumber     string `json:"phone_number"` // 关联查询出来的号码
	Category        string `json:"category"`
	Status          int    `json:"status"`
	ApplyTime       string `json:"apply_time"`
}

type OrderListReq struct {
	Page          int    `form:"page"`
	Size          int    `form:"size"`
	Status        int    `form:"status,optional"`         // 1-待沟通, 2-已办理...
	Keyword       string `form:"keyword,optional"`        // <--- 新增：用于模糊搜索
	PhoneNumber   string `form:"phone_number,optional"`   // 搜意向号码
	CustomerName  string `form:"customer_name,optional"`  // 搜客户名
	CustomerPhone string `form:"customer_phone,optional"` // 搜客户电话
}

type OrderListRes struct {
	Total int         `json:"total"`
	List  []OrderItem `json:"list"`
}

type HandleOrderReq struct {
	OrderId    int `json:"order_id"`
	Action     int `json:"action"`
	DistrictId int `json:"district_id,optional"` // <--- 新增
}

type DistrictStat struct {
	DistrictName  string `json:"district_name"`
	PendingCount  int64  `json:"pending_count"`  // 该区县待处理
	SoldCount     int64  `json:"sold_count"`     // 该区县已办理
	RejectedCount int64  `json:"rejected_count"` // 新增 已拒绝
}

type AnalysisRes struct {
	TotalPhones    int64          `json:"total_phones"`    // 号码池总数
	SoldPhones     int64          `json:"sold_phones"`     // 已办理/已售出总数
	PendingOrders  int64          `json:"pending_orders"`  // 当前待处理订单数
	RejectedOrders int64          `json:"rejected_orders"` // 已拒绝订单数
	DistrictStats  []DistrictStat `json:"district_stats"`  // 区县统计数据
}

type UserInfo struct {
	Id           int    `json:"id"`
	Username     string `json:"username"`
	NickName     string `json:"nick_name"`
	Role         string `json:"role"`          // admin, import_admin, district_admin
	DistrictId   int    `json:"district_id"`   // 0 表示不限
	DistrictName string `json:"district_name"` // 用于列表展示
	CreateTime   string `json:"create_time"`
}

type UserListRes struct {
	List  []UserInfo `json:"list"`
	Total int        `json:"total"`
}

type AddUserReq struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	NickName   string `json:"nick_name"`
	Role       string `json:"role"`                 // 必填
	DistrictId int    `json:"district_id,optional"` // 选填，仅 district_admin 需要
}

type UpdateUserReq struct {
	Id         int    `json:"id"`
	NickName   string `json:"nick_name"`
	Role       string `json:"role"`
	DistrictId int    `json:"district_id,optional"`
	Password   string `json:"password,optional"` // 留空则不修改
}

type LogItem struct {
	Id         int64  `json:"id"`
	Username   string `json:"username"`
	Action     string `json:"action"`
	Ip         string `json:"ip"`
	Ua         string `json:"ua"` // 浏览器信息
	CreateTime string `json:"create_time"`
}

type LogListReq struct {
	Page     int    `form:"page"`
	Size     int    `form:"size"`
	Username string `form:"username,optional"`
}

type LogListRes struct {
	List  []LogItem `json:"list"`
	Total int       `json:"total"`
}

type MiniNumberItem struct {
	Id         int     `json:"id"`
	FullNumber string  `json:"fullNumber"`
	Level      int     `json:"level"`
	LevelName  string  `json:"levelName"`
	Price      float64 `json:"price"` //  新增价格
	Category   string  `json:"category"`
	IsLocked   bool    `json:"isLocked"`
	Tag        string  `json:"tag"`
}

type MiniNumberListReq struct {
	Page     int    `form:"page"`
	PageSize int    `form:"pageSize"`
	Category string `form:"category,optional"`
	Level    int    `form:"level,optional"`
	Keyword  string `form:"keyword,optional"`
}

type MiniNumberListRes struct {
	List    []MiniNumberItem `json:"list"`
	Total   int              `json:"total"`
	HasMore bool             `json:"hasMore"`
}

type CheckStatusReq struct {
	NumberId   int    `json:"numberId"`
	FullNumber string `json:"fullNumber"`
	Openid     string `json:"openid"`
}

type CheckStatusRes struct {
	IsLocked   bool    `json:"isLocked"`
	LockedByMe bool    `json:"lockedByMe"`
	Price      float64 `json:"price"` //  返回价格方便前端计算
}

type SelectedNumber struct {
	Id         int     `json:"id"`
	FullNumber string  `json:"fullNumber"`
	Price      float64 `json:"price"`
}

type MiniCustomerInfo struct {
	Name       string `json:"name"`
	Phone      string `json:"phone"`
	DistrictId int    `json:"districtId"` //  新增：用户选择的区县ID
	Address    string `json:"address"`
	Remark     string `json:"remark,optional"`
}

type SubmitOrderReq struct {
	Openid          string           `json:"openid"`
	UserInfo        MiniCustomerInfo `json:"userInfo"` //  使用新名字
	SelectedNumbers []SelectedNumber `json:"selectedNumbers"`
	ApplyTime       string           `json:"applyTime,optional"` // 后端忽略此字段，使用 time.Now()
}

type SubmitOrderRes struct {
	OrderId    string `json:"orderId"`
	Status     string `json:"status"`
	ExpireTime string `json:"expireTime"`
}

type BannerRes struct {
	Image    string `json:"image"`
	Title    string `json:"title"`
	Subtitle string `json:"subtitle"`
}

type HistoryOrder struct {
	Id         string  `json:"id"`
	OrderId    string  `json:"orderId"`
	Number     string  `json:"number"`
	Type       string  `json:"type"`
	Level      string  `json:"level"`
	Status     string  `json:"status"`
	StatusText string  `json:"statusText"`
	Price      float64 `json:"price"`
	Time       string  `json:"time"` // 返回时间戳字符串
}

type HistoryReq struct {
	Openid   string `form:"openid"`
	Status   string `form:"status,optional"`
	Page     int    `form:"page"`
	PageSize int    `form:"pageSize"`
}

type HistoryRes struct {
	List  []HistoryOrder `json:"list"`
	Total int            `json:"total"`
}

type WxLoginReq struct {
	Code string `form:"code"`
}

type WxLoginRes struct {
	Openid string `json:"openid"`
	Token  string `json:"token"` // 这里可以返回 openid 作为临时 token
	Expire int64  `json:"expire"`
}
