// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "qianhao-backend/internal/handler/auth"
	manage "qianhao-backend/internal/handler/manage"
	mini "qianhao-backend/internal/handler/mini"
	system "qianhao-backend/internal/handler/system"
	"qianhao-backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/base/captcha",
				Handler: auth.GetCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/user/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/district/list",
				Handler: manage.GetDistrictsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/phone/import",
				Handler: manage.ImportPhonesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/phone/list",
				Handler: manage.ListPhonesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/order/create",
				Handler: manage.CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/order/list",
				Handler: manage.ListOrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/order/handle",
				Handler: manage.HandleOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/phone/delete",
				Handler: manage.DeletePhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/phone/update",
				Handler: manage.UpdatePhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/analysis/dashboard",
				Handler: manage.GetAnalysisHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/system/user/list",
				Handler: system.UserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/system/user/add",
				Handler: system.AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/system/user/update",
				Handler: system.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/system/user/delete",
				Handler: system.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/system/logs",
				Handler: system.GetLogListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/numbers",
				Handler: mini.GetNumbersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/numbers/check-status",
				Handler: mini.CheckStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders",
				Handler: mini.SubmitOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/banner",
				Handler: mini.GetBannerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/history",
				Handler: mini.GetHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/openid",
				Handler: mini.WxLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/mini"),
	)
}
